# Generated by Django 6.0.4 on 2026-05-27 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auction', '0001_initial'),
        ('item', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True, verbose_name='Quantidade')),
                ('unit_price', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Preco unitario')),
                ('subtotal', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Preco unitario')),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auction_items', to='auction.auction')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='item.item')),
            ],
            options={
                'verbose_name': 'Item de leilao',
                'verbose_name_plural': 'Itens de leilao',
                'ordering': ['id'],
            },
        ),
    ]
