# Generated by Django 6.0.4 on 2026-05-28 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctionitem', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionitem',
            old_name='subtotal',
            new_name='sub_total',
        ),
        migrations.RenameField(
            model_name='auctionitem',
            old_name='unit_price',
            new_name='value',
        ),
    ]
