# Generated by Django 6.0.4 on 2026-05-28 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Contactchannel',
            new_name='contactchannel',
        ),
    ]
