# Generated by Django 6.0.4 on 2026-05-29 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_contactchannel_user_contactchannel'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Saldo'),
        ),
        migrations.AddField(
            model_name='user',
            name='reputation',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Reputação'),
        ),
    ]
