# Generated by Django 6.0.4 on 2026-06-09 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_balance_user_reputation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.FloatField(blank=True, default=100000, null=True, verbose_name='Saldo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='reputation',
            field=models.FloatField(blank=True, default=10, null=True, verbose_name='Reputação'),
        ),
    ]
