# Generated by Django 6.0.4 on 2026-06-09 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_remove_payment_user'),
        ('user', '0004_alter_user_balance_alter_user_reputation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='payment',
            field=models.ManyToManyField(to='payment.payment', verbose_name='Metodos de pagamentos'),
        ),
    ]
