# Generated by Django 6.0.4 on 2026-05-28 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='user',
        ),
    ]
