# Generated by Django 6.0.4 on 2026-06-07 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_remove_auction_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='created_at',
        ),
    ]
