# Generated by Django 6.0.4 on 2026-05-27 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100, unique=True, verbose_name='Número')),
                ('issue_date', models.DateField(auto_now_add=True, verbose_name='Data de emissão')),
                ('auction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='auction.auction')),
            ],
            options={
                'verbose_name': 'Recibo',
                'verbose_name_plural': 'Recibos',
                'ordering': ['id'],
            },
        ),
    ]
