# Generated by Django 6.0.4 on 2026-06-07 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0003_remove_auction_created_at'),
        ('payment', '0003_alter_payment_auction_alter_payment_user'),
        ('receiptpayment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.payment'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='auction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auction.auction'),
        ),
    ]
