# Generated by Django 6.0.4 on 2026-05-28 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='date_sign',
        ),
    ]
