# Generated by Django 6.0.4 on 2026-05-29 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='payment_status',
            new_name='status',
        ),
    ]
