# Generated by Django 6.0.4 on 2026-06-07 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0003_remove_auction_created_at'),
        ('payment', '0002_rename_payment_status_payment_status'),
        ('user', '0003_user_balance_user_reputation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='auction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auction.auction'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
    ]
