# Generated by Django 6.0.4 on 2026-06-08 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_payment_auction_alter_payment_user'),
        ('user', '0003_user_balance_user_reputation'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Nome')),
                ('method', models.CharField(choices=[('C', 'Cartão de Crédito'), ('D', 'Débito'), ('P', 'Pix'), ('B', 'Boleto')], max_length=1, verbose_name='Tipo')),
                ('description', models.CharField(blank=True, max_length=120, verbose_name='Descrição')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='user.user')),
            ],
            options={
                'verbose_name': 'Método de pagamento',
                'verbose_name_plural': 'Métodos de pagamento',
                'ordering': ['id'],
            },
        ),
    ]
