# Generated by Django 6.0.4 on 2026-06-09 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_payment_description_payment_is_active_payment_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='auction',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='date_payment',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='total',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
    ]
