# Generated by Django 6.0.4 on 2026-06-09 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_remove_payment_auction_remove_payment_date_payment_and_more'),
        ('user', '0003_user_balance_user_reputation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Método de Pagamento', 'verbose_name_plural': 'Métodos de Pagamento'},
        ),
        migrations.RemoveField(
            model_name='payment',
            name='status',
        ),
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='user.user'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome do pagamento'),
        ),
    ]
