# Generated by Django 6.0.4 on 2026-06-09 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_alter_payment_options_remove_payment_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
    ]
