# Generated by Django 6.0.4 on 2026-05-27 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auctioneer',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='person.person')),
                ('company', models.CharField(max_length=100, verbose_name='Empresa')),
                ('evaluation', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Avaliacao')),
                ('commission', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Comissao')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Leiloeiro',
                'verbose_name_plural': 'Leiloeiros',
                'ordering': ['id'],
            },
            bases=('person.person',),
        ),
    ]
