# Generated by Django 6.0.4 on 2026-06-07 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctioneer', '0001_initial'),
        ('contactchannel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctioneer',
            name='contactchannel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contactchannel.contactchannel'),
        ),
    ]
