# Generated by Django 6.0.4 on 2026-06-03 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='doc',
        ),
        migrations.RemoveField(
            model_name='item',
            name='is_active',
        ),
    ]
